Arch: win64
CompatData: ''
Creation_Date: '2026-01-27 18:41:25.402640'
Custom_Path: true
DLL_Overrides:
    icu.dll: n,b
DXVK: dxvk-2.7.1-9-d6c19f9
Environment: Custom
Environment_Variables: {}
External_Programs:
    27620ba1-3382-4402-9514-af11b09303c4:
        executable: launcher.exe
        folder: /home/one/mount2/HoYoPlay
        id: 27620ba1-3382-4402-9514-af11b09303c4
        name: launcher
        path: /home/one/mount2/HoYoPlay/launcher.exe
Inherited_Environment_Variables:
- DBUS_SESSION_BUS_ADDRESS
- DISPLAY
- HOME
- LANG
- LC_ALL
- LC_CTYPE
- LC_MESSAGES
- PATH
- PULSE_SERVER
- TERM
- TZ
- USER
- WAYLAND_DISPLAY
- XAUTHORITY
- XDG_RUNTIME_DIR
Installed_Dependencies:
- d3dx9
- msls31
- arial32
- times32
- courie32
- d3dcompiler_43
- d3dcompiler_47
- mono
- gecko
- cjkfonts
Language: sys
LatencyFleX: latencyflex-v0.1.1-2-3bc9636
Limit_System_Environment: true
NVAPI: dxvk-nvapi-v0.9.0
Name: main2
Parameters:
    custom_dpi: 96
    decorated: true
    discrete_gpu: false
    dxvk: true
    dxvk_nvapi: false
    fixme_logs: false
    fsr: false
    fsr_quality_mode: none
    fsr_sharpening_strength: 2
    fullscreen_capture: false
    gamemode: false
    gamescope: false
    gamescope_borderless: false
    gamescope_fps: 0
    gamescope_fps_no_focus: 0
    gamescope_fullscreen: true
    gamescope_game_height: 0
    gamescope_game_width: 0
    gamescope_scaling: false
    gamescope_window_height: 0
    gamescope_window_width: 0
    latencyflex: false
    mangohud: false
    mangohud_display_on_game_start: true
    mouse_warp: true
    obsvkc: false
    pulseaudio_latency: false
    renderer: gl
    sandbox: false
    sync: fsync
    take_focus: false
    use_be_runtime: true
    use_eac_runtime: true
    use_runtime: false
    use_steam_runtime: false
    versioning_automatic: false
    versioning_compression: false
    versioning_exclusion_patterns: false
    virtual_desktop: false
    virtual_desktop_res: 1280x720
    vkbasalt: false
    vkd3d: true
    vmtouch: false
    vmtouch_cache_cwd: false
    wayland: false
    winebridge: false
Path: /home/one/Bottles/main2
Registry_Rules: []
Runner: ge-proton10-28
RunnerPath: ''
Sandbox:
    share_net: false
    share_sound: false
State: 0
Uninstallers: {}
Update_Date: '2026-01-27 21:07:42.919998'
VKD3D: vkd3d-proton-3.0
Versioning: false
Versioning_Exclusion_Patterns: []
Windows: win10
Winebridge: false
WorkingDir: ''
data: {}
run_in_terminal: false
session_arguments: ''
